name: Run Star Wars Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip xvfb wget unzip
        pip install -r requirements.txt
        # Install Google Chrome and Chromedriver
        wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
        rm google-chrome-stable_current_amd64.deb
        wget -N https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip
        # Install Firefox and Geckodriver
        sudo apt-get install -y firefox
        wget -N https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.29.1-linux64.tar.gz
        tar -xzf geckodriver-v0.29.1-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        rm geckodriver-v0.29.1-linux64.tar.gz
        # Install Microsoft Edge and Edgedriver
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/
        sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
        sudo rm microsoft.gpg
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable
        wget -N https://msedgedriver.azureedge.net/$(curl -s https://msedgedriver.azureedge.net/LATEST_RELEASE)/edgedriver_linux64.zip
        unzip edgedriver_linux64.zip
        sudo mv msedgedriver /usr/local/bin/
        rm edgedriver_linux64.zip

    - name: Run tests
      run: |
        chmod +x run_tests.sh
        ./run_tests.sh

    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results/
